---
displayName: "Builder for TOPPERS/JSP (target: m32r-m3a_2131)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "m32r-m3a_2131" ]
icon: https://camino.pizzafactory.jp/images/logos/toppers-open.svg
globalMemoryLimit: 1024Mi
