---
displayName: "Builder for TOPPERS/JSP (target: sh3-ms7727cp01)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "sh3-ms7727cp01" ]
icon: https://raw.githubusercontent.com/wiki/PizzaFactory/che-devfile-registry/toppers-open.svg
globalMemoryLimit: 1024Mi
