# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- pizzafactory

schedules:
- cron: "20 12 * * *"
  displayName: Daily build
  branches:
    include:
    - pizzafactory
  always: true

variables:
  containerRegistry: camino.azurecr.io
  organization: eclipse
  imageTag: nightly

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ./build.sh -r $(containerRegistry) -o $(organization) -t $(imageTag) --offline
  displayName: 'build'

- task: Docker@1
  inputs:
    command: login
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: camino.azurecr.io
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/pizzafactory'))

- script: docker push $(containerRegistry)/$(organization)/che-devfile-registry:$(imageTag)
  displayName: 'push to ACR'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/pizzafactory'))

- task: AzureCLI@2
  displayName: 'Imports images'
  inputs:
    azureSubscription: 'camino: BizSpark (1fbdb4bb-441e-4922-ba1f-ffd04f533ea1)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'git grep ''  image:'' devfiles | awk ''!/camino.azurecr.io|quay.io\/eclipse/ { print $NF }'' | sort | uniq | awk ''{print "az acr import --force --name camino --source " $0 }''| sh -x'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/pizzafactory'))
