---
displayName: "Builder for TOPPERS/JSP (target: mips32-malta)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "mips32-malta" ]
icon: https://camino.pizzafactory.jp/en/images/logos/toppen.svg
globalMemoryLimit: 1024Mi
