---
displayName: "Builder for TOPPERS/JSP (target: v850-tk850_sg2)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "v850-tk850_sg2" ]
icon: https://raw.githubusercontent.com/wiki/PizzaFactory/che-devfile-registry/toppers-open.svg
globalMemoryLimit: 1024Mi
