---
displayName: "Builder for TOPPERS/JSP (target: m32r-m3a_za36)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "m32r-m3a_za36" ]
icon: https://camino.pizzafactory.jp/en/images/logos/toppen.svg
globalMemoryLimit: 1024Mi
