---
displayName: Bitcoin-core
description: Environment for developing Bitcoin-core node.
tags: ["C/C++", "clang", "g++", "gdb", "Bitcoin", "Crypto-currency"]
icon: https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg
globalMemoryLimit: 3Gi
