---
displayName: "Builder for TOPPERS/JSP (target: sh3-solution_engine)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "sh3-solution_engine" ]
icon: https://camino.pizzafactory.jp/en/images/logos/toppen.svg
globalMemoryLimit: 1024Mi
