---
displayName: "Builder for TOPPERS/JSP (target: microblaze-suzaku)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "microblaze-suzaku" ]
icon: https://raw.githubusercontent.com/wiki/PizzaFactory/che-devfile-registry/toppers-open.svg
globalMemoryLimit: 1024Mi
