---
displayName: "Builder for TOPPERS/JSP (target: blackfin-bf533cb)"
description: GNU toolchains and TOPPERS/JSP tuned by PizzaFactory
tags: ["TOPPERS", "TOPPERS/JSP", "PizzaFactory", "ITRON", "blackfin-bf533cb" ]
icon: https://raw.githubusercontent.com/wiki/PizzaFactory/che-devfile-registry/toppers-open.svg
globalMemoryLimit: 1024Mi
