---
displayName: Test Modeling Environment
description: VSTeP/NGT Core modeling
tags: ["VSTeP/NGT", "OpenTestModeling"]
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
globalMemoryLimit: 1024Mi
